# Generated by Django 2.1 on 2019-01-03 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=50)),
                ('contribution', models.IntegerField(blank=True, default=0, null=True)),
                ('rating', models.IntegerField(blank=True, default=1400, null=True)),
                ('profilePhoto', models.ImageField(blank=True, null=True, upload_to='profilePhoto/%Y/%m/%D/')),
            ],
        ),
    ]
