# Generated by Django 2.1 on 2019-01-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190112_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='summary',
        ),
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=models.CharField(default='', max_length=6000),
        ),
    ]
