# Generated by Django 2.1 on 2019-01-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190114_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profilePhoto',
            field=models.ImageField(blank=True, default='https://userpic.codeforces.com/no-avatar.jpg', null=True, upload_to='profilePhoto/%Y/%m/%D/'),
        ),
    ]
