# Generated by Django 2.1 on 2019-01-15 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190114_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blogName',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
