# Generated by Django 2.1 on 2019-01-17 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190115_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Blog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.User')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='blogvote',
            unique_together={('blog', 'user')},
        ),
    ]
